[DEFAULT]
use_journal = True
# Disable stderr logging
use_stderr = False
debug = True
fatal_deprecations = False
my_ip = 172.29.236.13
osapi_volume_workers = 8
rootwrap_config = /etc/cinder/rootwrap.conf
api_paste_config = /etc/cinder/api-paste.ini
auth_strategy = keystone
## Cinder Scheduler
## RabbitMQ RPC
executor_thread_pool_size = 64
rpc_response_timeout = 60
transport_url = rabbit://cinder:a8a90cba493ac7d59d0aa6290@172.29.239.221:5671/cinder?ssl=1&ssl_version=TLSv1_2&ssl_ca_file=
## Quota
quota_volumes = 10
quota_snapshots = 10
quota_consistencygroups = 10
quota_gigabytes = 1000
quota_backups = 10
quota_backup_gigabytes = 1000
## Nova
nova_catalog_info = compute:nova:internalURL
nova_catalog_admin_info = compute:nova:adminURL
os_region_name = RegionOne
## Glance
glance_api_servers = http://172.29.236.11:9292
glance_num_retries = 0
glance_api_version = 2
volume_clear = zero
volume_clear_size = 0
volume_clear_ionice = -c3
volume_name_template = volume-%s
storage_availability_zone = nova
default_availability_zone = nova
target_helper = tgtadm
iscsi_iotype = fileio
target_ip_address = 172.29.244.13
iscsi_num_targets = 100
target_port = 3260
client_socket_timeout = 900
enabled_backends = ceph,lvm
# Ensure that user can create a new volume by cloning image-volume
allowed_direct_url_schemes = cinder
# All given backend(s)

[lvm]
iscsi_ip_address = 172.29.244.13
volume_backend_name = LVM_iSCSI
volume_driver = cinder.volume.drivers.lvm.LVMVolumeDriver
volume_group = cinder-volumes

[backend_defaults]
target_helper = tgtadm

[database]
connection = mysql+pymysql://cinder:b7d6316829f3c3393d1d9299a13717c499cdba8d63840480c5ddcf88@172.29.236.11:3306/cinder?charset=utf8&ssl_verify_cert=true
max_overflow = 50
max_pool_size = 5
pool_timeout = 30
connection_recycle_time = 600

[oslo_messaging_rabbit]
heartbeat_in_pthread = False
rabbit_quorum_queue = True
rabbit_transient_quorum_queue = True
rabbit_qos_prefetch_count = 10
use_queue_manager = False
rabbit_stream_fanout = True
rabbit_quorum_delivery_limit = 0
rabbit_quorum_max_memory_bytes = 0

[oslo_messaging_notifications]
driver = messagingv2
transport_url = rabbit://cinder:a8a90cba493ac7d59d0aa6290@172.29.239.221:5671/cinder?ssl=1&ssl_version=TLSv1_2&ssl_ca_file=

[oslo_concurrency]
lock_path = /run/lock/cinder

[profiler]
enabled = False
trace_sqlalchemy = False
hmac_keys = ea314922befd0ce3327d8bd470057756

[keystone_authtoken]
insecure = False
auth_type = password
auth_url = http://172.29.236.11:5000/v3
www_authenticate_uri = http://172.29.236.11:5000
project_domain_id = default
user_domain_id = default
project_name = service
username = cinder
password = b6863d3c170baca7f5a44089499463b4e78b0586b789f
region_name = RegionOne
memcached_servers = 172.29.239.254:11211
token_cache_time = 300
# if your memcached server is shared, use these settings to avoid cache poisoning
memcache_security_strategy = ENCRYPT
memcache_secret_key = 6082961501a8e352d50b0aa801100faa
service_token_roles_required = True
service_token_roles = service
service_type = volumev3

[nova]
interface = internal
insecure = False
auth_type = password
auth_url = http://172.29.236.11:5000/v3
password = b6863d3c170baca7f5a44089499463b4e78b0586b789f
project_domain_id = default
project_name = service
region_name = RegionOne
user_domain_id = default
username = cinder

[service_user]
send_service_user_token = True
insecure = False
auth_type = password
auth_url = http://172.29.236.11:5000/v3
password = b6863d3c170baca7f5a44089499463b4e78b0586b789f
project_domain_id = default
project_name = service
region_name = RegionOne
user_domain_id = default
username = cinder

[ceph]
volume_driver = cinder.volume.drivers.rbd.RBDDriver
volume_backend_name = ceph
rbd_pool = volumes
rbd_ceph_conf = /etc/ceph/ceph.conf
rbd_flatten_volume_from_snapshot = false
rbd_max_clone_depth = 5
rbd_store_chunk_size = 4
rados_connect_timeout = -1
rbd_user = cinder
rbd_secret_uuid = 457eb676-33da-42ec-9a8c-9293d545c337
