heat_template_version: 2021-04-16

resources:
  instance:
    type: OS::Heat::Stack
    properties:
      template: {get_file: nova.yml}
      parameters:
        flavor_name: m1.large #8_16384_100_gpu
        image_name: ubuntu-noble #cuda-offline-version
        private_net: memeservice #memeservice
        external_net: ext-net #ext-net, ext-vlan
        key_name: mynewkey
        software_opt: pt-cpu
        security_id: 7d716204-6c39-4cc0-9171-38f911fcfdbf
